---
- hosts: zabbix_agent
  become: yes

  tasks:

    - name: Copy Zabbix agent files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/etc/zabbix/zabbix_agentd.d/{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      loop:
        - { src: "task7.conf", dest: "task7.conf", mode: "0644" }
        - { src: "info.sh", dest: "info.sh", mode: "0755" }
        - { src: "test_python_script.py", dest: "test_python_script.py", mode: "0755" }
      notify: Restart zabbix-agent

  handlers:
    - name: Restart zabbix-agent
      ansible.builtin.systemd:
        name: zabbix-agent
        state: restarted